user  nginx;
worker_processes  auto;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    upstream flask_upstream {
        server app1:5000;
        server app2:5000;
    }

    server {
        listen 80;
        server_name _;

        location / {
            proxy_pass http://flask_upstream;
            # Force new upstream connection per request (disable keepalive reuse)
            proxy_http_version 1.1;
            proxy_set_header Connection "close";
            proxy_set_header Proxy-Connection "close";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Passthrough para métricas y health
        location /metrics {
            proxy_pass http://flask_upstream/metrics;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
